version: "3.8"

services:
  app:
    build: .
    container_name: cat_etl_app
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=catdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: postgres_cat
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  pg_data:
